# site settings

title: Sajid
description: ... writing software, capturing random moments ...
taglong: ... writing software, capturing random moments ...
tagshort: ... software & photography ...
url: https://reznov9185.github.io
permalink: pretty
repo: https://github.com/Reznov9185/reznov9185.github.io

# author settings

author:
  name: Sajidur Rahman
  email: reznov9185@gmail.com
photo: /assets/jpg/sajid_prof.jpg

# social media links

social:
  github: Reznov9185
  instagram: reznov9185
  linkedin: sajidcse
  substack: https://substack.com/@sajid9185
  gscholar: https://scholar.google.com/citations?user=oznop_EAAAAJ&hl=en

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
